name: service unit test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: ubuntu-s-1vcpu-2gb-sgp1-01

    # services:
    #   mongo:
    #     image: mongo:6.0
    #     ports:
    #       - 27017:27017
    #     options: >-
    #       --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
    #       --health-interval=10s 
    #       --health-timeout=5s 
    #       --health-retries=5
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: check dir list
      #   run: ls -l && pwd
      
      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.12.0
        # with:
        #   mongodb-version: ${{ matrix.mongodb-version }}  

      - uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'

      - name: Install mongosh
        run: |
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
       
      - name: check mongosh    
        run: mongosh --version
        
      - name: mongosh connect  
        run: mongosh "mongodb://localhost:27017" --eval "db.stats()"
          
      # - name: Check MongoDB connection
      #   run: |
      #     curl -sL https://www.mongodb.org/static/pgp/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server.gpg
      #     echo "deb [signed-by=/usr/share/keyrings/mongodb-server.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      #     sudo apt-get update
      #     sudo apt-get install -y mongodb-org-shell
      #     mongosh "mongodb://localhost:27017" --eval "db.stats()"
    
      # - name: Check MongoDB
      #   run: mongod --version


      # - name: check mongod
      #   run: mongod --version


      # - name: Check MongoDB connection
      #   run: |
      #     until mongosh "mongodb://localhost:27017" --eval "db.stats()"; do
      #       echo "Waiting for MongoDB to be ready..."
      #       sleep 2
      #     done
